site_name: MkDocs Learning Material Generator
site_description: インタラクティブな学習資料を自動生成するシステム
repo_url: https://github.com/example/mkdocs-learning-material
repo_name: mkdocs-learning-material
theme:
  name: material
  palette:
    primary: blue-grey
    accent: cyan
  features:
  - navigation.tabs
  - search.suggest
  - toc.integrate
  - header.autohide
  - announce.dismiss
  - content.tooltips
  locale: ja
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.tabbed
- attr_list
- md_in_html
- footnotes
- tables
- fenced_code
- abbr
- pymdownx.snippets
plugins: []
extra_javascript:
- custom.js
extra_css:
- custom.css
extra: {}
nav:
- IT・組み込み技術入門:
  - ホーム: test_material/index.md
  - '第1章: 基本要素': test_material/documents/chapter01.md
  - '第2章: ツールチップ': test_material/documents/chapter02.md
  - '第3章: 図表': test_material/documents/chapter03.md
  - '第4章: 演習': test_material/documents/chapter04.md
  - '第5章: 統合テスト': test_material/documents/chapter05.md
  - 用語集: test_material/glossary.md
  - FAQ: test_material/faq.md
  - TIPS: test_material/tips.md
