extra: {}
extra_css:
- custom_dark.css
- custom.css
- custom_high_contrast.css
extra_javascript:
- quiz.js
- quizzes_data.js
- interactive.js
- custom.js
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:mermaid2.fence_mermaid_custom
      name: mermaid
- pymdownx.highlight
- pymdownx.tabbed
- pymdownx.tasklist
- attr_list
- md_in_html
- footnotes
- tables
- fenced_code
- abbr
- pymdownx.snippets
- pymdownx.emoji
- pymdownx.keys
nav:
- IT・組み込み技術入門:
  - ホーム: test_material/index.md
  - 用語集: test_material/glossary.md
  - FAQ: test_material/faq.md
  - TIPS: test_material/tips.md
plugins:
- search
- mermaid2:
    version: 10.6.1
repo_name: mkdocs-learning-material
repo_url: https://github.com/example/mkdocs-learning-material
site_description: インタラクティブな学習資料を自動生成するシステム
site_name: MkDocs Learning Material Generator
theme:
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  - toc.integrate
  - header.autohide
  - content.tooltips
  - content.code.copy
  - content.code.annotate
  locale: ja
  name: material
  palette:
  - accent: cyan
    media: '(prefers-color-scheme: light)'
    primary: blue
    scheme: default
    toggle:
      icon: material/brightness-7
      name: ダークモードに切り替え
  - accent: cyan
    media: '(prefers-color-scheme: dark)'
    primary: blue
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: ライトモードに切り替え
