extra: {}
extra_css:
- custom.css
- custom_high_contrast.css
- custom_dark.css
extra_javascript:
- quiz.js
- custom.js
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.highlight
- pymdownx.tabbed
- pymdownx.tasklist
- attr_list
- md_in_html
- footnotes
- tables
- fenced_code
- abbr
- pymdownx.snippets
- pymdownx.emoji
- pymdownx.keys
nav:
- ホーム: index.md
- テスト教材:
  - 概要: test_material/documents/index.md
  - 第1章: test_material/documents/chapter01.md
  - 第2章: test_material/documents/chapter02.md
  - 第3章: test_material/documents/chapter03.md
  - 第4章: test_material/documents/chapter04.md
  - 第5章: test_material/documents/chapter05.md
  - 第6章: test_material/documents/chapter06.md
  - 用語集: glossary.md
  - FAQ: faq.md
  - TIPS: tips.md
plugins:
- search
repo_name: mkdocs-learning-material
repo_url: https://github.com/example/mkdocs-learning-material
site_description: インタラクティブな学習資料を自動生成するシステム
site_name: MkDocs Learning Material Generator
theme:
  features:
  - navigation.tabs
  - search.suggest
  - toc.integrate
  - header.autohide
  - announce.dismiss
  - content.tooltips
  locale: ja
  name: material
  palette:
    accent: amber
    primary: blue
