site_name: MkDocs Learning Material Generator
site_description: インタラクティブな学習資料を自動生成するシステム
repo_url: https://github.com/example/mkdocs-learning-material
repo_name: mkdocs-learning-material

theme:
  name: material
  palette:
    primary: blue
    accent: amber
  features:
    - navigation.tabs
    - search.suggest
    - toc.integrate
    - header.autohide
    - announce.dismiss
    - content.tooltips
  locale: ja

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - fenced_code
  - abbr
  - pymdownx.snippets

nav:
  - ホーム: index.md