# 教材全体の基本設定とメタデータを定義します。
site_name: "Core機能テスト教材"
author: "Gemini"
theme:
  primary_color: "indigo"
  accent_color: "pink"
# ラーニングパス用のメタデータ
prerequisites: []
next_steps: []
# ページに付与する共通タグ
tags:
  - core-test
  - example
